#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme


# Site Settings
title: STARS
tagline: A CSHL DNA Learning Center summer-research camp and mentoring program
email: williams@cshl.edu
description: >
permalink: pretty
